env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - google
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns: ["**/*.d.ts"]
rules:
  quotes:
    - error
    - double
  no-unused-vars:
    - error
  no-console:
    - error
settings:
  react:
    pragma: React
    version: detect
