env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - google
  - prettier
overrides:
  [
    {
      "files": ["**/__tests__/**"],
      "plugins": ["jest"],
      "extends": ["plugin:jest/recommended", "prettier"],
      "rules":
        { "require-jsdoc": "off", "jest/prefer-expect-assertions": "off" },
    },
    {
      "files": ["**/*.tsx", "**/*.ts"],
      "plugins": ["react", "react-hooks", "@typescript-eslint", "prettier"],
      "extends":
        [
          "eslint:recommended",
          "plugin:react/all",
          "plugin:react-hooks/recommended",
          "plugin:@typescript-eslint/recommended-type-checked",
        ],
      "parserOptions": { "project": ["./tsconfig.json"] },
      "rules": {
          "@typescript-eslint/explicit-function-return-type": "error",
          "react/jsx-filename-extension": ["error", { "extensions": [".tsx"] }],
          # Style rule, unneeded with Prettier
          "react/jsx-indent": "off",
          # Style rule, unneeded with Prettier
          "react/jsx-indent-props": "off",
          # Style rule, unneeded with Prettier
          "react/jsx-one-expression-per-line": "off",
          # Style rule, unneeded with Prettier
          "react/jsx-max-props-per-line": "off",
          # Style rule, unneeded with Prettier
          "react/jsx-newline": "off",
        },
    },
  ]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ["**/*.d.ts"]
rules:
  quotes:
    - error
    - double
  no-unused-vars:
    - error
  no-console:
    - error
settings:
  react:
    pragma: React
    version: detect
