env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/all
  - plugin:@typescript-eslint/recommended
  - google
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns: ["**/*.d.ts"]
rules:
  quotes:
    - error
    - double
  no-unused-vars:
    - error
  no-console:
    - error
  react/jsx-filename-extension:
    - error
    - extensions: [".tsx"]
  react/require-default-props:
    # https://stackoverflow.com/a/69746922/5476186
    - off
settings:
  react:
    pragma: React
    version: detect
