name: Build
on: [push]

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        run: |
          npm install -g yarn
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Check Formatting
        run: yarn prettier --check .
      - name: Compile Check
        run: yarn tsc
      - name: Lint Check
        run: yarn lint
      - name: Dependency Audit
        run: yarn audit
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        run: npm install -g yarn
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Unit Tests
        run: yarn test
        # Run coverage separately; longer build, but when there's a failure it'll be easier to understand why.
      - name: Unit Test Coverage
        run: yarn test --coverage
