# https://github.com/marketplace/actions/todo-to-issue
name: Log TODO Issues

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log the TODO Issues
        uses: alstr/todo-to-issue-action@v4
